# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45afd04cfe279c9de4269eb8146939f3a345bc4bcd93d8f7f408a297e764d85254674ecbb50f845c57d99b66033fb1d83c99971320b643be0d21320d4a6574a8

test:
  secret_key_base: af067f18aec7f84c1fc258ba12c9d807704bd1c2dde16ed8ff6c41d5f86feb39562f3463a12e74dd1d2a7a55f4c81c7fa452400ac37bd1777fd8f91247d080a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
